# config.yaml
data_path:      "data/raw"
img_path:       "data/img"
need_convert:   False
check_file:     False
convert_algo:   "bin_to_img"
cuda_idx:       3
num_class:      6
train_rate:     0.7
num_epochs:     50
batch_size:     32
learning_rate:  .001
momentum:       0.9
weight_decay:   1
num_workers:    4